'''
容器序列
    list、tuple和collections.deque这些序列能存放不同的数据。
    可变序列
        list、bytearray、array.array、collections.deque和memoryview
    不可变系列
        tuple、str和bytes
扁平序列
    str、bytes、bytearray、memoryview和array.array，这类序列只能容纳一种类型。
    容器序列是存放的是它们所包含的任意类型的对象引用，而扁平序列里存放的是值而不是引用。
'''
